# Generated by Django 4.0 on 2022-09-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_customuser_profile_picture_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question_app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
