# Generated by Django 4.0 on 2022-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0004_favorite_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_for_question_and_user'),
        ),
    ]
